import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Download,
  GitCommit,
  GitBranch,
  Percent,
} from "lucide-react";
import Header from "../../components/layout/Header";
import StatsCard from "../../components/analysis/StatsCard";
import RoleDistributionChart from "../../components/analysis/RoleDistributionChart";
import ContributionList from "../../components/analysis/ContributionList";
import LoadingSpinner from "../../components/common/LoadingSpinner";

interface ContributionStats {
  id: string;
  userId: string;
  repositoryFullName: string;
  totalCommits: number;
  userCommits: number;
  commitPercentage: number;
  additions?: number;
  deletions?: number;
  roleDistribution?: Record<string, RoleStats>;
  analyzedAt: string;
}

interface RoleStats {
  roleName: string;
  commitCount: number;
  percentage: number;
}

interface PullRequest {
  number: number;
  title: string;
  state: string;
  htmlUrl: string;
  createdAt: string;
  closedAt?: string;
  mergedAt?: string;
}

interface Issue {
  number: number;
  title: string;
  state: string;
  htmlUrl: string;
  createdAt: string;
  closedAt?: string;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateMarkdownReport(
  stats: ContributionStats,
  prs: PullRequest[],
  issues: Issue[],
  owner: string,
  repo: string
): string {
  const date = new Date().toLocaleDateString("ko-KR");

  let markdown = `# ${repo} 기여도 리포트\n\n`;
  markdown += `**생성일:** ${date}\n`;
  markdown += `**레포지토리:** ${owner}/${repo}\n\n`;

  markdown += `## 📊 기본 통계\n\n`;
  markdown += `- **총 커밋 수:** ${stats.totalCommits}개\n`;
  markdown += `- **내 커밋 수:** ${stats.userCommits}개\n`;
  markdown += `- **기여도:** ${stats.commitPercentage.toFixed(1)}%\n`;
  markdown += `- **코드 변경:** +${stats.additions} / -${stats.deletions} 라인\n\n`;

  if (stats.roleDistribution) {
    markdown += `## 🎯 역할 분석\n\n`;
    Object.values(stats.roleDistribution).forEach((role) => {
      markdown += `- **${role.roleName}:** ${role.percentage.toFixed(1)}% (${
        role.commitCount
      }개)\n`;
    });
    markdown += `\n`;
  }

  markdown += `## 🔧 구현한 기능 (Pull Requests)\n\n`;
  if (prs.length > 0) {
    prs.forEach((pr) => {
      const status = pr.mergedAt ? "✅" : pr.state === "closed" ? "❌" : "🔄";
      markdown += `- ${status} ${pr.title} (#${pr.number})\n`;
    });
  } else {
    markdown += `- Pull Request가 없습니다.\n`;
  }
  markdown += `\n`;

  markdown += `## 🐛 해결한 문제 (Issues)\n\n`;
  if (issues.length > 0) {
    issues.forEach((issue) => {
      const status = issue.state === "closed" ? "✅" : "🔄";
      markdown += `- ${status} ${issue.title} (#${issue.number})\n`;
    });
  } else {
    markdown += `- Issue가 없습니다.\n`;
  }
  markdown += `\n`;

  markdown += `---\n*Generated by Tally*\n`;

  return markdown;
}

function generateHTMLReport(
  stats: ContributionStats,
  prs: PullRequest[],
  issues: Issue[],
  owner: string,
  repo: string
): string {
  const date = new Date().toLocaleDateString("ko-KR");

  let html = `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${repo} 기여도 리포트</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      max-width: 800px;
      margin: 50px auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 10px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    h1 {
      color: #333;
      border-bottom: 3px solid #5b75ff;
      padding-bottom: 10px;
    }
    h2 {
      color: #555;
      margin-top: 30px;
    }
    .stats {
      background: #e8f5e9;
      padding: 20px;
      border-radius: 5px;
      margin: 20px 0;
    }
    .stats p {
      margin: 10px 0;
      font-size: 16px;
    }
    .role-item {
      padding: 10px;
      margin: 5px 0;
      background: #f0f4ff;
      border-left: 4px solid #5b75ff;
      border-radius: 4px;
    }
    .list-item {
      padding: 10px;
      margin: 5px 0;
      background: #f9f9f9;
      border-left: 4px solid #5b75ff;
      border-radius: 4px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      color: #999;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>📈 ${repo} 기여도 리포트</h1>
    <p><strong>생성일:</strong> ${date}</p>
    <p><strong>레포지토리:</strong> ${owner}/${repo}</p>
    
    <div class="stats">
      <h2>📊 기본 통계</h2>
      <p><strong>총 커밋 수:</strong> ${stats.totalCommits}개</p>
      <p><strong>내 커밋 수:</strong> ${stats.userCommits}개</p>
      <p><strong>기여도:</strong> ${stats.commitPercentage.toFixed(1)}%</p>
      <p><strong>코드 변경:</strong> +${stats.additions} / -${
    stats.deletions
  } 라인</p>
    </div>
    
    <h2>🎯 역할 분석</h2>`;

  if (stats.roleDistribution) {
    Object.values(stats.roleDistribution).forEach((role) => {
      html += `<div class="role-item"><strong>${
        role.roleName
      }:</strong> ${role.percentage.toFixed(1)}% (${role.commitCount}개)</div>`;
    });
  }

  html += `<h2>🔧 구현한 기능 (Pull Requests)</h2>`;
  if (prs.length > 0) {
    prs.forEach((pr) => {
      const status = pr.mergedAt ? "✅" : pr.state === "closed" ? "❌" : "🔄";
      html += `<div class="list-item">${status} ${pr.title} <small>(#${pr.number})</small></div>`;
    });
  } else {
    html += `<p>Pull Request가 없습니다.</p>`;
  }

  html += `<h2>🐛 해결한 문제 (Issues)</h2>`;
  if (issues.length > 0) {
    issues.forEach((issue) => {
      const status = issue.state === "closed" ? "✅" : "🔄";
      html += `<div class="list-item">${status} ${issue.title} <small>(#${issue.number})</small></div>`;
    });
  } else {
    html += `<p>Issue가 없습니다.</p>`;
  }

  html += `
    <div class="footer">
      <p>Generated by Tally</p>
    </div>
  </div>
</body>
</html>`;

  return html;
}

export default function Analysis() {
  const { owner, repo } = useParams<{ owner: string; repo: string }>();
  const navigate = useNavigate();

  const [stats, setStats] = useState<ContributionStats | null>(null);
  const [pullRequests, setPullRequests] = useState<PullRequest[]>([]);
  const [issues, setIssues] = useState<Issue[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    fetchAnalysisData();
  }, [owner, repo]);

  const fetchAnalysisData = async () => {
    try {
      setIsLoading(true);

      await new Promise((resolve) => setTimeout(resolve, 1500));

      const mockStats: ContributionStats = {
        id: "1",
        userId: "user1",
        repositoryFullName: `${owner}/${repo}`,
        totalCommits: 150,
        userCommits: 87,
        commitPercentage: 58.0,
        additions: 3245,
        deletions: 1120,
        roleDistribution: {
          backend: { roleName: "백엔드", commitCount: 65, percentage: 74.7 },
          frontend: {
            roleName: "프론트엔드",
            commitCount: 15,
            percentage: 17.2,
          },
          infrastructure: {
            roleName: "인프라",
            commitCount: 7,
            percentage: 8.1,
          },
        },
        analyzedAt: new Date().toISOString(),
      };

      const mockPRs: PullRequest[] = [
        {
          number: 12,
          title: "feat: GitHub OAuth 인증 구현",
          state: "closed",
          htmlUrl: `https://github.com/${owner}/${repo}/pull/12`,
          createdAt: "2025-10-01T10:00:00Z",
          mergedAt: "2025-10-01T15:30:00Z",
        },
        {
          number: 15,
          title: "feat: 기여도 분석 엔진 추가",
          state: "closed",
          htmlUrl: `https://github.com/${owner}/${repo}/pull/15`,
          createdAt: "2025-10-03T09:00:00Z",
          mergedAt: "2025-10-03T16:00:00Z",
        },
        {
          number: 18,
          title: "fix: 리포트 생성 버그 수정",
          state: "open",
          htmlUrl: `https://github.com/${owner}/${repo}/pull/18`,
          createdAt: "2025-10-07T14:00:00Z",
        },
      ];

      const mockIssues: Issue[] = [
        {
          number: 8,
          title: "성능 최적화 필요",
          state: "closed",
          htmlUrl: `https://github.com/${owner}/${repo}/issues/8`,
          createdAt: "2025-09-28T11:00:00Z",
          closedAt: "2025-10-02T16:00:00Z",
        },
        {
          number: 11,
          title: "에러 처리 개선",
          state: "closed",
          htmlUrl: `https://github.com/${owner}/${repo}/issues/11`,
          createdAt: "2025-10-01T13:00:00Z",
          closedAt: "2025-10-04T10:00:00Z",
        },
        {
          number: 14,
          title: "문서 업데이트",
          state: "open",
          htmlUrl: `https://github.com/${owner}/${repo}/issues/14`,
          createdAt: "2025-10-05T09:00:00Z",
        },
      ];

      setStats(mockStats);
      setPullRequests(mockPRs);
      setIssues(mockIssues);
    } catch (error) {
      console.error("Failed to fetch analysis data:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadMarkdown = async () => {
    if (!stats || !owner || !repo) return;

    try {
      setIsDownloading(true);

      const content = generateMarkdownReport(
        stats,
        pullRequests,
        issues,
        owner,
        repo
      );
      downloadFile(content, `${repo}-contribution-report.md`, "text/markdown");
    } catch (error) {
      console.error("Markdown 다운로드 실패:", error);
      alert("리포트 다운로드에 실패했습니다.");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleDownloadHTML = async () => {
    if (!stats || !owner || !repo) return;

    try {
      setIsDownloading(true);

      const content = generateHTMLReport(
        stats,
        pullRequests,
        issues,
        owner,
        repo
      );
      downloadFile(content, `${repo}-contribution-report.html`, "text/html");
    } catch (error) {
      console.error("HTML 다운로드 실패:", error);
      alert("리포트 다운로드에 실패했습니다.");
    } finally {
      setIsDownloading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Header />
        <LoadingSpinner />
      </div>
    );
  }

  if (!stats) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Header />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center">
            <h2 className="text-2xl font-bold text-gray-900">
              데이터를 불러올 수 없습니다
            </h2>
            <button
              onClick={() => navigate("/dashboard")}
              className="mt-4 btn-primary"
            >
              대시보드로 돌아가기
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <button
            onClick={() => navigate("/dashboard")}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900 mb-4 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>대시보드로 돌아가기</span>
          </button>

          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">{repo}</h1>
              <p className="text-gray-600 mt-1">
                {owner} / {repo}
              </p>
            </div>

            <div className="flex gap-3">
              <button
                onClick={handleDownloadMarkdown}
                disabled={isDownloading}
                className="btn-secondary flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download className="w-4 h-4" />
                {isDownloading ? "다운로드 중..." : "Markdown"}
              </button>
              <button
                onClick={handleDownloadHTML}
                disabled={isDownloading}
                className="btn-primary flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Download className="w-4 h-4" />
                {isDownloading ? "다운로드 중..." : "HTML"}
              </button>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <StatsCard
            icon={GitCommit}
            label="총 커밋 수"
            value={stats.totalCommits}
            subValue="전체 프로젝트"
            color="primary"
          />
          <StatsCard
            icon={GitBranch}
            label="내 커밋 수"
            value={stats.userCommits}
            subValue={`${stats.commitPercentage.toFixed(1)}% 기여`}
            color="success"
          />
          <StatsCard
            icon={Percent}
            label="기여도"
            value={`${stats.commitPercentage.toFixed(1)}%`}
            subValue={`+${stats.additions} / -${stats.deletions} 라인`}
            color="secondary"
          />
        </div>

        {stats.roleDistribution && (
          <div className="mb-8">
            <RoleDistributionChart
              data={{
                backend: stats.roleDistribution.backend?.commitCount || 0,
                frontend: stats.roleDistribution.frontend?.commitCount || 0,
                infrastructure:
                  stats.roleDistribution.infrastructure?.commitCount || 0,
                test: stats.roleDistribution.test?.commitCount || 0,
                documentation:
                  stats.roleDistribution.documentation?.commitCount || 0,
                configuration:
                  stats.roleDistribution.configuration?.commitCount || 0,
                other: stats.roleDistribution.other?.commitCount || 0,
              }}
            />
          </div>
        )}

        <ContributionList pullRequests={pullRequests} issues={issues} />
      </div>
    </div>
  );
}
